In [1]:
import numpy as np
array_14 = np.array([[1, 2, 1],[2, 1, 1],[1, 1, 2]])
determinant_14 = round(np.linalg.det(array_14))
print('array 14 =\n', array_14,'\n', 'determinant for array 14 = ', determinant_14,'\n')

array_15 = np.array([[2, 1, 2],[1, 2, 2],[2, 2, 1]])
determinant_15 = round(np.linalg.det(array_15))
print('array 15 =\n', array_15,'\n', 'determinant for array 15 = ', determinant_15,'\n')

array_16 = np.array([[1, 2, 3],[3, 1, 2],[2, 3, 1]])
determinant_16 = round(np.linalg.det(array_16))
print('array 16 =\n', array_16,'\n', 'determinant for array 16 = ', determinant_16,'\n')

array_17 = np.array([[1, 2, 1],[2, 4, 2],[1, 1, 2]])
determinant_17 = round(np.linalg.det(array_17))
print('array 17 =\n', array_17,'\n', 'determinant for array 17 = ', determinant_17,'\n')

array_18 = np.array([[1, 2, 3],[3, 6, 9],[2, 3, 1]])
determinant_18 = round(np.linalg.det(array_18))
print('array 18 =\n', array_18,'\n', 'determinant for array 18 = ', determinant_18,'\n')

array_19 = np.array([[1, 1, 3],[3, 3, 2],[2, 2, 1]])
determinant_19 = round(np.linalg.det(array_19))
print('array 19 =\n', array_19,'\n', 'determinant for array 19 = ', determinant_19,'\n')

array_20 = np.array([[1, 2, -2],[3, 1, -1],[2, 3, -3]])
determinant_20 = round(np.linalg.det(array_20))
print('array 20 =\n', array_20,'\n', 'determinant for array 20 = ', determinant_20,'\n')

array_21 = np.array([[1, -1, 2],[-2, 1, 1],[1, -2, 2]])
determinant_21 = round(np.linalg.det(array_21))
print('array 21 =\n', array_21,'\n', 'determinant for array 21 = ', determinant_21,'\n')

array_22 = np.array([[3, -2, -1],[2, -3, 1],[1, -2, -3]])
determinant_22 = round(np.linalg.det(array_22))
print('array 22 =\n', array_22,'\n', 'determinant for array 22 = ', determinant_22,'\n')

array_23 = np.array([[1, 4, 3],[2, -5, 1],[1, -3, 2]])
determinant_23 = round(np.linalg.det(array_23))
print('array 23 =\n', array_23,'\n', 'determinant for array 23 = ', determinant_23,'\n')

array_24 = np.array([[0, 0, 1],[3, 1, 2],[0, 3, 1]])
determinant_24 = round(np.linalg.det(array_24))
print('array 24 =\n', array_24,'\n', 'determinant for array 24 = ', determinant_24,'\n')

array_25 = np.array([[1, 2, 1],[3, 0, 0],[2, 3, 1]])
determinant_25 = round(np.linalg.det(array_25))
print('array 25 =\n', array_25,'\n', 'determinant for array 25 = ', determinant_25,'\n')

array_26 = np.array([[1, 2, 3],[3, 1, 2],[0, 1, 0]])
determinant_26 = round(np.linalg.det(array_26))
print('array 26 =\n', array_26,'\n', 'determinant for array 26 = ', determinant_26,'\n')

array_27 = np.array([[1, 0, 0],[3, 1, -2],[2, 3, 1]])
determinant_27 = round(np.linalg.det(array_27))
print('array 27 =\n', array_27,'\n', 'determinant for array 27 = ', determinant_27,'\n')

array_28 = np.array([[1, 2, 3],[0, 1, 2],[0, 3, -1]])
determinant_28 = round(np.linalg.det(array_28))
print('array 28 =\n', array_28,'\n', 'determinant for array 28 = ', determinant_28,'\n')

array_29 = np.array([[1, 2, 3],[3, 0, 2],[2, 0, 1]])
determinant_29 = round(np.linalg.det(array_29))
print('array 29 =\n', array_29,'\n', 'determinant for array 29 = ', determinant_29,'\n')

array_30 = np.array([[1, 2, 0],[1, 4, 0],[2, 3, 1]])
determinant_30 = round(np.linalg.det(array_30))
print('array 30 =\n', array_30,'\n', 'determinant for array 30 = ', determinant_30,'\n')

array 14 =
 [[1 2 1]
 [2 1 1]
 [1 1 2]] 
 determinant for array 14 =  -4.0 

array 15 =
 [[2 1 2]
 [1 2 2]
 [2 2 1]] 
 determinant for array 15 =  -5.0 

array 16 =
 [[1 2 3]
 [3 1 2]
 [2 3 1]] 
 determinant for array 16 =  18.0 

array 17 =
 [[1 2 1]
 [2 4 2]
 [1 1 2]] 
 determinant for array 17 =  0.0 

array 18 =
 [[1 2 3]
 [3 6 9]
 [2 3 1]] 
 determinant for array 18 =  0.0 

array 19 =
 [[1 1 3]
 [3 3 2]
 [2 2 1]] 
 determinant for array 19 =  0.0 

array 20 =
 [[ 1  2 -2]
 [ 3  1 -1]
 [ 2  3 -3]] 
 determinant for array 20 =  0.0 

array 21 =
 [[ 1 -1  2]
 [-2  1  1]
 [ 1 -2  2]] 
 determinant for array 21 =  5.0 

array 22 =
 [[ 3 -2 -1]
 [ 2 -3  1]
 [ 1 -2 -3]] 
 determinant for array 22 =  20.0 

array 23 =
 [[ 1  4  3]
 [ 2 -5  1]
 [ 1 -3  2]] 
 determinant for array 23 =  -22.0 

array 24 =
 [[0 0 1]
 [3 1 2]
 [0 3 1]] 
 determinant for array 24 =  9.0 

array 25 =
 [[1 2 1]
 [3 0 0]
 [2 3 1]] 
 determinant for array 25 =  3.0 

array 26 =
 [[1 2 3]
 [3 1 2]
 [0 1 0]] 
 dete